//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\appxdeploymentserver.dll
// Interface ID: ae2dc901-312d-41df-8b79-e835e63db874
// Interface Version: 1.0
// Client Generated: 2024-01-22 6:36:21 PM
// NtApiDotNet Version: 1.1.32

namespace rpc_ae2dc901_312d_41df_8b79_e835e63db874_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_2(Struct_3 p0)
        {
            WriteStruct<Struct_3>(p0);
        }
        public void Write_3(Struct_4 p0)
        {
            WriteStruct<Struct_4>(p0);
        }
        public void Write_4(Struct_5 p0)
        {
            WriteStruct<Struct_5>(p0);
        }
        public void Write_5(Struct_6 p0)
        {
            WriteStruct<Struct_6>(p0);
        }
        public void Write_6(Struct_7 p0)
        {
            WriteStruct<Struct_7>(p0);
        }
        public void Write_7(Struct_8 p0)
        {
            WriteStruct<Struct_8>(p0);
        }
        public void Write_8(Struct_9 p0)
        {
            WriteStruct<Struct_9>(p0);
        }
        public void Write_9(Struct_3[] p0, long p1)
        {
            WriteConformantStructArray<Struct_3>(p0, p1);
        }
        public void Write_10(int[] p0)
        {
            WriteFixedPrimitiveArray<int>(p0, 2);
        }
        public void Write_11(string p0)
        {
            WriteFixedString(p0, 48);
        }
        public void Write_12(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_13(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_14(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_15(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_16(NtApiDotNet.NtToken p0)
        {
            WriteSystemHandle<NtApiDotNet.NtToken>(p0);
        }
        public void Write_17(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_18(NtApiDotNet.NtEvent p0)
        {
            WriteSystemHandle<NtApiDotNet.NtEvent>(p0);
        }
        public void Write_19(NtApiDotNet.NtEvent[] p0, long p1)
        {
            WriteConformantArrayCallback<NtApiDotNet.NtEvent>(p0, new System.Action<NtApiDotNet.NtEvent>(this.Write_18), p1);
        }
        public void Write_20(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_21(int[] p0, long p1)
        {
            WriteConformantArray<int>(p0, p1);
        }
        public void Write_22(long[] p0, long p1)
        {
            WriteConformantArray<long>(p0, p1);
        }
        public void Write_23(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_24(char[] p0, long p1)
        {
            WriteConformantArray<char>(p0, p1);
        }
        public void Write_25(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_26(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_27(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public Struct_2 Read_1()
        {
            return ReadStruct<Struct_2>();
        }
        public Struct_3 Read_2()
        {
            return ReadStruct<Struct_3>();
        }
        public Struct_4 Read_3()
        {
            return ReadStruct<Struct_4>();
        }
        public Struct_5 Read_4()
        {
            return ReadStruct<Struct_5>();
        }
        public Struct_6 Read_5()
        {
            return ReadStruct<Struct_6>();
        }
        public Struct_7 Read_6()
        {
            return ReadStruct<Struct_7>();
        }
        public Struct_8 Read_7()
        {
            return ReadStruct<Struct_8>();
        }
        public Struct_9 Read_8()
        {
            return ReadStruct<Struct_9>();
        }
        public Struct_3[] Read_9()
        {
            return ReadConformantStructArray<Struct_3>();
        }
        public int[] Read_10()
        {
            return ReadFixedPrimitiveArray<int>(2);
        }
        public string Read_11()
        {
            return ReadFixedString(48);
        }
        public string[] Read_12()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public string[] Read_13()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public string[] Read_14()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public string[] Read_15()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public NtApiDotNet.NtToken Read_16()
        {
            return ReadSystemHandle<NtApiDotNet.NtToken>();
        }
        public string[] Read_17()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public NtApiDotNet.NtEvent Read_18()
        {
            return ReadSystemHandle<NtApiDotNet.NtEvent>();
        }
        public NtApiDotNet.NtEvent[] Read_19()
        {
            return ReadConformantArrayCallback<NtApiDotNet.NtEvent>(new System.Func<NtApiDotNet.NtEvent>(this.Read_18));
        }
        public string[] Read_20()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public int[] Read_21()
        {
            return ReadConformantArray<int>();
        }
        public long[] Read_22()
        {
            return ReadConformantArray<long>();
        }
        public string[] Read_23()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public char[] Read_24()
        {
            return ReadConformantArray<char>();
        }
        public byte[] Read_25()
        {
            return ReadConformantArray<byte>();
        }
        public string[] Read_26()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public string[] Read_27()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEnum16(Member0);
            m.WriteInt64(Member8);
            m.WriteInt64(Member10);
            m.WriteEmbeddedPointer<string>(Member18, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member20, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member28, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(Member30);
            m.WriteEmbeddedPointer<System.Guid>(Member38, new System.Action<System.Guid>(m.WriteGuid));
            m.WriteInt32(Member40);
            m.WriteInt32(Member44);
            m.WriteEmbeddedPointer<string>(Member48, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member50, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member58, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member60, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt64(Member68);
            m.WriteEmbeddedPointer<string>(Member70, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<Struct_2>(Member78, new System.Action<Struct_2>(m.Write_1));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEnum16();
            Member8 = u.ReadInt64();
            Member10 = u.ReadInt64();
            Member18 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member20 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member28 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member30 = u.ReadInt32();
            Member38 = u.ReadEmbeddedPointer<System.Guid>(new System.Func<System.Guid>(u.ReadGuid), false);
            Member40 = u.ReadInt32();
            Member44 = u.ReadInt32();
            Member48 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member50 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member58 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member60 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member68 = u.ReadInt64();
            Member70 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member78 = u.ReadEmbeddedPointer<Struct_2>(new System.Func<Struct_2>(u.Read_1), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member0;
        public long Member8;
        public long Member10;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member18;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member20;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member28;
        public int Member30;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<System.Guid> Member38;
        public int Member40;
        public int Member44;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member48;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member50;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member58;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member60;
        public long Member68;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member70;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_2> Member78;
        public static Struct_0 CreateDefault()
        {
            return new Struct_0();
        }
        public Struct_0(
                    NtApiDotNet.Ndr.Marshal.NdrEnum16 Member0, 
                    long Member8, 
                    long Member10, 
                    string Member18, 
                    string Member20, 
                    string Member28, 
                    int Member30, 
                    System.Nullable<System.Guid> Member38, 
                    int Member40, 
                    int Member44, 
                    string Member48, 
                    string Member50, 
                    string Member58, 
                    string Member60, 
                    long Member68, 
                    string Member70, 
                    System.Nullable<Struct_2> Member78)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member28 = Member28;
            this.Member30 = Member30;
            this.Member38 = Member38;
            this.Member40 = Member40;
            this.Member44 = Member44;
            this.Member48 = Member48;
            this.Member50 = Member50;
            this.Member58 = Member58;
            this.Member60 = Member60;
            this.Member68 = Member68;
            this.Member70 = Member70;
            this.Member78 = Member78;
        }
    }
    public struct Struct_2 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<Struct_3[], long>(Member8, new System.Action<Struct_3[], long>(m.Write_9), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_3[]>(new System.Func<Struct_3[]>(u.Read_9), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_3[]> Member8;
        public static Struct_2 CreateDefault()
        {
            return new Struct_2();
        }
        public Struct_2(int Member0, Struct_3[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_3 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<string>(Member0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member8, new System.Action<string>(m.WriteTerminatedString));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member8 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member8;
        public static Struct_3 CreateDefault()
        {
            return new Struct_3();
        }
        public Struct_3(string Member0, string Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_4 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_10(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member0, "Member0"));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_10();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int[] Member0;
        public static Struct_4 CreateDefault()
        {
            Struct_4 ret = new Struct_4();
            ret.Member0 = new int[2];
            return ret;
        }
        public Struct_4(int[] Member0)
        {
            this.Member0 = Member0;
        }
    }
    public struct Struct_5 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<string>(Member0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member8, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member10, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member18, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt16(Member20);
            m.WriteInt64(Member28);
            m.WriteInt32(Member30);
            m.WriteInt32(Member34);
            m.WriteInt32(Member38);
            m.WriteInt32(Member3C);
            m.WriteInt32(Member40);
            m.WriteEmbeddedPointer<string>(Member48, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member50, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member58, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member60, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member68, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member70, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member78, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<Struct_5>(Member80, new System.Action<Struct_5>(m.Write_4));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member8 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member10 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member18 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member20 = u.ReadInt16();
            Member28 = u.ReadInt64();
            Member30 = u.ReadInt32();
            Member34 = u.ReadInt32();
            Member38 = u.ReadInt32();
            Member3C = u.ReadInt32();
            Member40 = u.ReadInt32();
            Member48 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member50 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member58 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member60 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member68 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member70 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member78 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member80 = u.ReadEmbeddedPointer<Struct_5>(new System.Func<Struct_5>(u.Read_4), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member10;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member18;
        public short Member20;
        public long Member28;
        public int Member30;
        public int Member34;
        public int Member38;
        public int Member3C;
        public int Member40;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member48;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member50;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member58;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member60;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member68;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member70;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member78;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_5> Member80;
        public static Struct_5 CreateDefault()
        {
            return new Struct_5();
        }
        public Struct_5(
                    string Member0, 
                    string Member8, 
                    string Member10, 
                    string Member18, 
                    short Member20, 
                    long Member28, 
                    int Member30, 
                    int Member34, 
                    int Member38, 
                    int Member3C, 
                    int Member40, 
                    string Member48, 
                    string Member50, 
                    string Member58, 
                    string Member60, 
                    string Member68, 
                    string Member70, 
                    string Member78, 
                    System.Nullable<Struct_5> Member80)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member28 = Member28;
            this.Member30 = Member30;
            this.Member34 = Member34;
            this.Member38 = Member38;
            this.Member3C = Member3C;
            this.Member40 = Member40;
            this.Member48 = Member48;
            this.Member50 = Member50;
            this.Member58 = Member58;
            this.Member60 = Member60;
            this.Member68 = Member68;
            this.Member70 = Member70;
            this.Member78 = Member78;
            this.Member80 = Member80;
        }
    }
    public struct Struct_6 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<string>(Member0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEnum16(Member8);
            m.WriteEmbeddedPointer<Struct_6>(Member10, new System.Action<Struct_6>(m.Write_5));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member8 = u.ReadEnum16();
            Member10 = u.ReadEmbeddedPointer<Struct_6>(new System.Func<Struct_6>(u.Read_5), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_6> Member10;
        public static Struct_6 CreateDefault()
        {
            return new Struct_6();
        }
        public Struct_6(string Member0, NtApiDotNet.Ndr.Marshal.NdrEnum16 Member8, System.Nullable<Struct_6> Member10)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
        }
    }
    public struct Struct_7 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_11(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member0, "Member0"));
            m.WriteInt64(Member60);
            m.WriteInt64(Member68);
            m.WriteEmbeddedPointer<Struct_7>(Member70, new System.Action<Struct_7>(m.Write_6));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_11();
            Member60 = u.ReadInt64();
            Member68 = u.ReadInt64();
            Member70 = u.ReadEmbeddedPointer<Struct_7>(new System.Func<Struct_7>(u.Read_6), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public string Member0;
        public long Member60;
        public long Member68;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_7> Member70;
        public static Struct_7 CreateDefault()
        {
            Struct_7 ret = new Struct_7();
            ret.Member0 = new string('\0', 48);
            return ret;
        }
        public Struct_7(string Member0, long Member60, long Member68, System.Nullable<Struct_7> Member70)
        {
            this.Member0 = Member0;
            this.Member60 = Member60;
            this.Member68 = Member68;
            this.Member70 = Member70;
        }
    }
    public struct Struct_8 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<Struct_9>(Member0, new System.Action<Struct_9>(m.Write_8));
            m.WriteEmbeddedPointer<string>(Member8, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member10, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member18, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member20, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(Member28);
            m.WriteEnum16(Member2C);
            m.WriteInt32(Member30);
            m.WriteInt64(Member38);
            m.WriteInt64(Member40);
            m.WriteEmbeddedPointer<Struct_8>(Member48, new System.Action<Struct_8>(m.Write_7));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<Struct_9>(new System.Func<Struct_9>(u.Read_8), false);
            Member8 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member10 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member18 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member20 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member28 = u.ReadInt32();
            Member2C = u.ReadEnum16();
            Member30 = u.ReadInt32();
            Member38 = u.ReadInt64();
            Member40 = u.ReadInt64();
            Member48 = u.ReadEmbeddedPointer<Struct_8>(new System.Func<Struct_8>(u.Read_7), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_9> Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member10;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member18;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member20;
        public int Member28;
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member2C;
        public int Member30;
        public long Member38;
        public long Member40;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_8> Member48;
        public static Struct_8 CreateDefault()
        {
            return new Struct_8();
        }
        public Struct_8(System.Nullable<Struct_9> Member0, string Member8, string Member10, string Member18, string Member20, int Member28, NtApiDotNet.Ndr.Marshal.NdrEnum16 Member2C, int Member30, long Member38, long Member40, System.Nullable<Struct_8> Member48)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member28 = Member28;
            this.Member2C = Member2C;
            this.Member30 = Member30;
            this.Member38 = Member38;
            this.Member40 = Member40;
            this.Member48 = Member48;
        }
    }
    public struct Struct_9 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<string>(Member0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member8, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<Struct_9>(Member10, new System.Action<Struct_9>(m.Write_8));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member8 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member10 = u.ReadEmbeddedPointer<Struct_9>(new System.Func<Struct_9>(u.Read_8), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_9> Member10;
        public static Struct_9 CreateDefault()
        {
            return new Struct_9();
        }
        public Struct_9(string Member0, string Member8, System.Nullable<Struct_9> Member10)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("ae2dc901-312d-41df-8b79-e835e63db874", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int AppXApplyTrustLabelToFolder(
                    Struct_0 p0, 
                    int p1, 
                    string[] p2, 
                    int p3, 
                    string[] p4, 
                    int p5, 
                    string[] p6, 
                    int p7, 
                    string[] p8, 
                    Struct_4 p9, 
                    long p10, 
                    NtApiDotNet.NtToken p11, 
                    out string p12, 
                    out int p13, 
                    out int p14, 
                    out string p15)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_0(p0);
            m.WriteInt32(p1);
            m.WriteReferent(p2, new System.Action<string[], long>(m.Write_12), p1);
            m.WriteInt32(p3);
            m.WriteReferent(p4, new System.Action<string[], long>(m.Write_13), p3);
            m.WriteInt32(p5);
            m.WriteReferent(p6, new System.Action<string[], long>(m.Write_14), p5);
            m.WriteInt32(p7);
            m.WriteReferent(p8, new System.Action<string[], long>(m.Write_15), p7);
            m.Write_3(p9);
            m.WriteInt64(p10);
            m.Write_16(p11);
            _Unmarshal_Helper u = SendReceive(0, m);
            p12 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            p13 = u.ReadInt32();
            p14 = u.ReadInt32();
            p15 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_1(out Struct_4 p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(1, m);
            p0 = u.Read_3();
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_2(Struct_4 p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_3(p0);
            m.WriteEnum16(p1);
            _Unmarshal_Helper u = SendReceive(2, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_3()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(3, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_4(string p0, int p1, out System.Nullable<Struct_5> p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(4, m);
            p2 = u.ReadReferentValue<Struct_5>(new System.Func<Struct_5>(u.Read_4), false);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_5(string p0, string p1, string p2, int p3, out System.Nullable<Struct_5> p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(5, m);
            p4 = u.ReadReferentValue<Struct_5>(new System.Func<Struct_5>(u.Read_4), false);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_6(string p0, string p1, int p2, out NtApiDotNet.Ndr.Marshal.NdrEnum16 p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(6, m);
            p3 = u.ReadEnum16();
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_7(string p0, out System.Nullable<Struct_6> p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(7, m);
            p1 = u.ReadReferentValue<Struct_6>(new System.Func<Struct_6>(u.Read_5), false);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_8(string p0, out int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(8, m);
            p1 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_9(string p0, sbyte p1, int p2, string[] p3, out NtApiDotNet.NtEvent[] p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteSByte(p1);
            m.WriteInt32(p2);
            m.Write_17(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"), p2);
            _Unmarshal_Helper u = SendReceive(9, m);
            p4 = u.Read_19();
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_10(string p0, string p1, out System.Nullable<Struct_5> p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            _Unmarshal_Helper u = SendReceive(10, m);
            p2 = u.ReadReferentValue<Struct_5>(new System.Func<Struct_5>(u.Read_4), false);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_11(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0, string p1, int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(11, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_12(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0, string p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            _Unmarshal_Helper u = SendReceive(12, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_13(string p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteEnum16(p1);
            _Unmarshal_Helper u = SendReceive(13, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_14(string p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, System.Guid p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteEnum16(p1);
            m.WriteGuid(p2);
            _Unmarshal_Helper u = SendReceive(14, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_15(string[] p0, int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_20(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"), p1);
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(15, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_16(string p0, int p1, int p2, int p3, int[] p4, out long[] p5, out long p6)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteInt32(p1);
            m.WriteInt32(p2);
            m.WriteInt32(p3);
            m.Write_21(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p4, "p4"), p3);
            _Unmarshal_Helper u = SendReceive(16, m);
            p5 = u.Read_22();
            p6 = u.ReadInt64();
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_17(string p0, string p1, int p2, out System.Nullable<Struct_5> p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(17, m);
            p3 = u.ReadReferentValue<Struct_5>(new System.Func<Struct_5>(u.Read_4), false);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_18(out System.Nullable<Struct_5> p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(18, m);
            p0 = u.ReadReferentValue<Struct_5>(new System.Func<Struct_5>(u.Read_4), false);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_19(string[] p0, int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_23(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"), p1);
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(19, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_20(int p0, string p1, string p2, string p3, string p4, string p5, int p6, out System.Nullable<Struct_5> p7)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteReferent(p2, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p4, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p5, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(p6);
            _Unmarshal_Helper u = SendReceive(20, m);
            p7 = u.ReadReferentValue<Struct_5>(new System.Func<Struct_5>(u.Read_4), false);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_21(string p0, long p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(21, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_22(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(22, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_23(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(23, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_24(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(24, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_25(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(25, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_26(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(26, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_27(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(27, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_28(string p0, long p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(28, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_29(string p0, long p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(29, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_30(string p0, string p1, string p2, string p3, int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p2, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(p4);
            _Unmarshal_Helper u = SendReceive(30, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_31(string p0, string p1, string p2, string p3, int p4, int p5, ref char[] p6, out int p7)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p2, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(p4);
            m.WriteInt32(p5);
            m.Write_24(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p6, "p6"), p5);
            _Unmarshal_Helper u = SendReceive(31, m);
            p6 = u.Read_24();
            p7 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_32(string p0, string p1, string p2, string p3, int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p2, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(p4);
            _Unmarshal_Helper u = SendReceive(32, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_33(string p0, int p1, byte[] p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(p1);
            m.WriteReferent(p2, new System.Action<byte[], long>(m.Write_25), p1);
            _Unmarshal_Helper u = SendReceive(33, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_34(string p0, out int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(34, m);
            p1 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_35(System.Guid p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteEnum16(p1);
            _Unmarshal_Helper u = SendReceive(35, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_36(string p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteEnum16(p1);
            _Unmarshal_Helper u = SendReceive(36, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_37()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(37, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_38(long p0, System.Guid p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt64(p0);
            m.WriteGuid(p1);
            _Unmarshal_Helper u = SendReceive(38, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_39(long p0, string p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt64(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            _Unmarshal_Helper u = SendReceive(39, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_40(string p0, int p1, string[] p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteInt32(p1);
            m.Write_12(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"), p1);
            _Unmarshal_Helper u = SendReceive(40, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_41(string p0, string p1, int p2, int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(p2);
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(41, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_42(int p0, string[] p1, string p2, out int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.Write_26(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"), p0);
            m.WriteReferent(p2, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(42, m);
            p3 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_43(int p0, string[] p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.WriteReferent(p1, new System.Action<string[], long>(m.Write_27), p0);
            _Unmarshal_Helper u = SendReceive(43, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_44(System.Guid p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            _Unmarshal_Helper u = SendReceive(44, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_45(string p0, string p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(45, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_46(string p0, int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(46, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_47(string[] p0, int p1, int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_20(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"), p1);
            m.WriteInt32(p1);
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(47, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_48()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(48, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_49(string p0, string p1, long p2, string p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt64(p2);
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(49, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_50(out System.Nullable<Struct_7> p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(50, m);
            p0 = u.ReadReferentValue<Struct_7>(new System.Func<Struct_7>(u.Read_6), false);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_51(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(51, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_52()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(52, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_53(out int p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(53, m);
            p0 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_54(string p0, out string p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(54, m);
            p1 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_55(string p0, long p1, long p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt64(p1);
            m.WriteInt64(p2);
            _Unmarshal_Helper u = SendReceive(55, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_56(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(56, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_57(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(57, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_58(string p0, out string p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(58, m);
            p1 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            return u.ReadInt32();
        }
        public int MergeSystemResourceFilesImplementation()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(59, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_60(string p0, string p1, out int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            _Unmarshal_Helper u = SendReceive(60, m);
            p2 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_61(out System.Nullable<Struct_8> p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(61, m);
            p0 = u.ReadReferentValue<Struct_8>(new System.Func<Struct_8>(u.Read_7), false);
            return u.ReadInt32();
        }
        public int MergeSystemResourceFilesImplementation_62(string p0, out int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(62, m);
            p1 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_63(string p0, int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(63, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_64(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(64, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_65(string p0, out int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(65, m);
            p1 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_66(string p0, int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(66, m);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_67(string p0, string p1, out string p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            _Unmarshal_Helper u = SendReceive(67, m);
            p2 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            return u.ReadInt32();
        }
        public int AppXApplyTrustLabelToFolder_68(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(68, m);
            return u.ReadInt32();
        }

        //ADDED FOR WIN11 SUPPORT - PNAC - 2024-01-23
        public int AppXSetTrustLabelOnPackage_59(string p0, out string p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(59, m);
            p1 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            return u.ReadInt32();
        }
    }
    #endregion
}

